# Rules: https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml
# Compose: https://detekt.dev/docs/introduction/compose
style:
  NewLineAtEndOfFile:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 250
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: [ 'Preview' ]
  UnusedPrivateProperty:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
  OptionalWhenBraces:
    active: false
  UseRequire:
    active: false


complexity:
  LongParameterList:
    active: true
    ignoreAnnotated: [ 'Composable' ]
  LongMethod:
    active: true
    ignoreAnnotated: [ 'Composable' ]
  TooManyFunctions: # TODO (rittmann) can be useful, but need to ignore for UI, see it later
    active: false

naming:
  PackageNaming:
    active: true
    packagePattern: '([a-z]+(\.[a-z][a-z_]*)*)'
  FunctionNaming:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false