name: CI

on:
  push:
    branches: [ "test_pipeline" ]
  pull_request:
    branches: [ "test_pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: "adopt"

      - name: Detekt
        uses: natiginfo/action-detekt-all@1.23.4
        with:
          args:  --config ./config/detekt/detekt.yml

      - name: Gradle
        run: ./gradlew build
        # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless